config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "circles#index"
  get "circles/search"
  get "circles/genre"
  resources :circles do
    get "joing"
    get "withdrawal"
    resources :articles, except: [:index]
    resources :events, except: [:index, :destroy] do
      get "attend"
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :user_events
  has_many :users, through: :user_events
  has_one :author_circle_user, -> { where(author: true) }, class_name: 'UserEvent'
  has_one :author_user, through: :author_circle_user, source: :user
  belongs_to :circle

  with_options presence: true do
    validates :title
    validates :body
    validates :start_time
    validates :end_time
  end

  def attendance(other_user)
    users << other_user
  end

  def absence(other_user)
    users.delete(other_user)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :sign_in_user?
  before_action :set_circle
  before_action :ser_event, only: [:show, :edit, :update]
  before_action :circle_user?
  before_action :author_user?, only: [:edit]

  def new
    @event = @circle.events.new
  end

  def create
    @event = @circle.events.new(event_params)
    if @event.save
      redirect_to @circle
    else
      render :new
    end
  end

  def show
    @users = @event.users
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to circle_event_path(@circle, @event)
    else
      render :edit
    end
  end

  def attend
    @event = Event.find(params[:event_id])
    if @event.users.include?(current_user)
      @event.absence(current_user)
    else
      @event.attendance(current_user)
    end
    redirect_to circle_event_path(@circle, @event)
  end

  private

  def event_params
    params.require(:event)
          .permit(:title, :body, :start_time, :end_time, :circle_id, :author)
          .merge(author_user: current_user)
  end

  def sign_in_user?
    return redirect_to new_user_session_path unless signed_in?
  end

  def set_circle
    @circle = Circle.find(params[:circle_id])
  end

  def ser_event
    @event = Event.find(params[:id])
  end

  def circle_user?
    return redirect_to root_path unless @circle.users.include?(current_user)
  end

  def author_user?
    redirect_to root_path unless @event.author_user == current_user
  end
end

app/views/events/_form.html.erb
<div class="container">
	<div class="jumbotron">
		<h1 class="display-4"><%= yield(:page_title) %></h1>
	</div>
	<%= form_with model: [circle,event] do |f|%>
		<div class="form-group">
			<%= f.label :title%>
			<%= f.text_field :title, class:"form-control"%>
		</div>
		<div class="form-group">
			<%= f.label :start_time%>
			<%= f.datetime_field :start_time%>
		</div>
		<div class="form-group">
			<%= f.label :end_time %>
			<%= f.datetime_field :end_time %>
		</div>
		<div class="form-group">
			<%= f.label :body%>
			<%= f.text_area :body, class:"form-control content"%>
		</div>
		<div class="form-group">
			<%= f.submit yield(:send_title), class:"btn btn-success" %>
		</div>
	<% end %>
</div>

app/views/events/edit.html.erb
<% provide(:page_title, "イベント編集") %>
<% provide(:send_title, "更新") %>
<%= render 'form', event: @event, circle: @circle%>

app/views/events/new.html.erb
<% provide(:page_title, "新規イベント作成") %>
<% provide(:send_title, "作成") %>
<%= render 'form', event: @event, circle: @circle%>

app/views/events/show.html.erb
<div class="container">
	<div class="jumbotron">
		<h1 class="display-4"><%= @event.title %></h1>
		<%= @event.start_time.strftime('%Y/%m/%d %H:%M:%S') %> ~ <%= @event.end_time.strftime('%Y/%m/%d %H:%M:%S') %>
		<hr class="my-4">
		<% if @event.author_user == current_user%>
			<%= link_to "編集", edit_circle_event_path(@circle, @event), class: "btn btn-primary btn-lg" %>
		<% end %>
		<%= link_to "出欠登録", circle_event_attend_path(@circle, @event), class: "btn btn-info btn-lg" %>
	</div>
	<div class="row justify-content-md-center">
		<div class="col-md-auto">
			<h2>詳細</h2>
    </div>
  </div>
	<div class="row justify-content-md-center">
		<div class="article-content">
			<%= @event.body%>
		</div>
	</div>
	<br>
	<ul class="list-group">
		<h2>参加者</h2>
		<% @users.each do |user| %>
  		<li class="list-group-item"><%= user.nickname %></li>
		<% end %>
	</ul>
	<div class="row justify-content-md-center">
		<%= link_to "戻る", circle_path(@circle), class:"btn btn-primary" %>
	</div>
</div>