config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "circles#index"
  get "circles/search"
  get "circles/genre"
  resources :circles do
    get "joing"
    get "withdrawal"
    resources :articles, except: [:index]
    resources :events, except: [:index, :destroy] do
      get "attend"
    end
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/circle.rb
class Circle < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :user_circles, dependent: :destroy
  has_many :users, through: :user_circles
  has_many :articles
  has_many :events
  has_one :leader_circle_user, -> { where(leader: true) }, class_name: 'UserCircle'
  has_one :leader_user, through: :leader_circle_user, source: :user
  has_one_attached :image
  belongs_to_active_hash :genre
  belongs_to_active_hash :prefecture

  with_options presence: true do
    validates :name
    validates :phrase
    validates	:description, length: { maximum: 1000 }
    validates :genre_id, numericality: { other_than: 1 }
    validates :activity
    validates :age_range
    validates :prefecture_id, numericality: { other_than: 1 }
    validates :city
  end

  def invite(other_users)
    users << other_users
  end

  def withdrawal(other_user)
    users.delete(other_user)
  end

  private

  def should_not_destroy
    return throw :abort unless leader_user == current_user
  end
end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController
  before_action :sign_in_user?, only: [:new, :edit, :joing, :withdrawal]
  before_action :set_circle, only: [:show, :edit, :update, :destroy]
  before_action :set_users, only: [:new, :edit, :create, :update]
  before_action :leader_user?, only: [:edit]
  before_action :serach_circle, only: [:index, :search, :genre]

  def index
    @circles = Circle.all.with_attached_image.order(created_at: 'DESC')
    @genres = Genre.all.where.not(id: 1)
  end

  def new
    @circle = Circle.new
  end

  def create
    @circle = Circle.new(circle_params)
    if @circle.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @users = @circle.users
    @articles = @circle.articles
    @events = @circle.events
  end

  def edit
  end

  def update
    if @circle.update(circle_params)
      redirect_to circle_path(@circle)
    else
      render :edit
    end
  end

  def destroy
    if @circle.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def joing
    @circle = Circle.find(params[:circle_id])
    if @circle.users.include?(current_user)
      redirect_to root_path
    else
      @circle.invite(current_user)
      redirect_to circle_path(@circle)
    end
  end

  def withdrawal
    @circle = Circle.find(params[:circle_id])
    if @circle.leader_user == current_user
      redirect_to circle_path(@circle)
    else
      @circle.withdrawal(current_user)
      redirect_to root_path
    end
  end

  def search
    @results = @p.result(distinct: true)
  end

  def genre
    @circles = Circle.all.where(genre_id: params[:genre])
  end

  private

  def circle_params
    params.require(:circle)
          .permit(:name, :phrase, :description, :genre_id, :activity, :age_range, :prefecture_id, :city,
                  :leader, :image, user_ids: [])
          .merge(leader_user: current_user)
  end

  def sign_in_user?
    return redirect_to new_user_session_path unless signed_in?
  end

  def set_circle
    @circle = Circle.find(params[:id])
  end

  def set_users
    @users = User.where.not(id: current_user)
  end

  def leader_user?
    redirect_to root_path unless @circle.leader_user == current_user
  end

  def serach_circle
    @p = Circle.ransack(params[:q])
  end
end

app/views/circles/_circle_head.html.erb
<div class="jumbotron">
	<h1 class="display-4"><%= circle.name %></h1>
	<p class="lead"><%= circle.phrase %></p>
	<hr class="my-4">
	<%= image_tag circle.image, class: "circle-img" if circle.image.attached?%>
</div>

app/views/circles/_form.html.erb
<div class='account-page__inner--right user-form'>
	<%= form_with model: circle, local: true do |f| %>
		<%= render "/shared/error_message", model: f.object %>
		<%= f.file_field :image, class: "form_image" %>
		<img class="prev-content" style="width:100px;height:100px;">
		<div class='field'>
			<div class='field-label'>
				<%= f.label :name%>
			</div>
			<div class='field-input'>
				<%= f.text_field :name, autofocus: true%>
			</div>
			<div class='field-label'>
				<%= f.label :phrase %>
			</div>
			<div class='field-input'>
				<%= f.text_field :phrase, autofocus: true%>
			</div>
		</div>
		<div class='field'>
			<div class='field-label'>
				<%= f.label :description %>
			</div>
			<div class='field-input'>
				<%= f.text_area :description, class:"form-control" %>
			</div>
		</div>
		<div class='field'>
			<div class='field-label'>
				<%= f.label :genre_id %>
			</div>
			<div class='field-input'>
				<%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"form-control"}) %>
			</div>
			<div class='field-label'>
				<%= f.label :activity %>
			</div>
			<div class='field-input'>
				<%= f.text_field :activity, autofocus: true%>
			</div>
			<div class='field-label'>
				<%= f.label :age_range %>
			</div>
			<div class='field-input'>
				<%= f.text_field :age_range, autofocus: true%>
			</div>
			<div class='field-label'>
				<%= f.label :prefecture_id %>
			</div>
			<div class='field-input'>
				<%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"form-control"}) %>
			</div>
			<div class='field-label'>
				<%= f.label :city %>
			</div>
			<div class='field-input'>
				<%= f.text_field :city, autofocus: true%>
			</div>
			<div class="row">
				<%= f.collection_check_boxes(:user_ids, @users, :id, :nickname) do |b| %>
					<div class="col user_index">
						<%= b.label { b.check_box + b.text } %>
					</div>
				<% end %>
			</div>
		</div>
		<div class='actions'>
			<%= f.submit yield(:send_title), class: 'btn'%>
		</div>
	</div>
<% end %>

app/views/circles/_search_form.html.erb
<div class="row row-cols-4">
	<%= search_form_for search, url: circles_search_path, class:"form-row search-form" do |f| %>
		<%= f.label :name_or_phrase_or_description_or_activity_or_age_range_or_city_cont, "キーワード" %>
		<%= f.text_field :name_or_phrase_or_description_or_activity_or_age_range_or_city_cont, class:"form-control mb-2"%>
		<div class="col">
			<%= f.label :genre_id_eq, "ジャンル" %>
			<%= f.collection_select(:genre_id_eq, Genre.all, :id, :name, {include_blank: '指定なし' }, {class:"form-control"}) %>
		</div>
		<div class="col">
			<%= f.label :prefecture_id_eq, "都道府県" %>
			<%= f.collection_select(:prefecture_id_eq, Prefecture.all, :id, :name, {include_blank: '指定なし' }, {class:"form-control"}) %>
		</div>
		<%= f.submit '検索', class:"search-btn" %>
	<% end %>
</div>

app/views/circles/article.html.erb
<div class="container">
	<%= render "circles/circle_head", circle: @circle %>
	<%= form_with model: @article do |f| %>
		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class:"form-control", id:"exampleFormControlInput1", placeholder:"タイトルを入力してください" %>
		</div>
		<div class="form-group">
			<%= f.label :content %>
			<textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
		</div>
		<div class="form-group">
			<%= f.submit "送信", class:"btn btn-success" %>
		</div>
	<% end %>
</div>

app/views/circles/edit.html.erb
<% provide(:send_title, "Update Circle") %>
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Circle</h2>
      <h5>サークルを編集</h5>
    </div>
    <%= render "form", circle: @circle %>
  </div>
</div>

app/views/circles/genre.html.erb
<div class="container">
	<h3>検索</h3>
	<%= render "search_form", search: @p %>
	<h3>検索結果</h3>
	<br>
	<% if @circles %>
		<% @circles.each do |circle| %>
			<div class="p-2 bd-highlight circle-list">
				<%= link_to circle.name, circle_path(circle) %>
				<br>
				<%= image_tag circle.image, class: "circle-img" if circle.image.attached?%>
				<%= circle.phrase %>
			</div>
			<br>
		<% end %>
	<% end %>
</div>

app/views/circles/index.html.erb
<div class="container">
	<div class="row justify-content-md-center">
		<h1 class="display-4">Circle Of Friends</h1>
	</div>
	<h3>検索</h3>
	<%= render "search_form", search: @p%>
	<h3>サークル一覧</h3>
	<div class="d-flex flex-column bd-highlight mb-3">
		<% @circles.each do |circle| %>
		<div class="p-2 bd-highlight circle-list">
			<h4><%= link_to circle.name, circle_path(circle) %></h4>
			<br>
			<div class="circle-index">
				<%= image_tag circle.image, class: "circle-img" if circle.image.attached?%>
				<div class="circle-info">
					<p class="font-weight-bold">
						<%= circle.phrase %>
					</p>
					<span class="d-inline-block text-truncate" style="max-width: 800px;">
						【サークル説明】<%= circle.description %>
					</span>
					<br>
					<p class="font-weight-normal">
						【ジャンル】<%= circle.genre.name %>
					</p>
					<p class="font-weight-normal">
						【年齢層】<%= circle.age_range %>
					</p>
				</div>
			</div>
		</div>
		<% end %>
	</div>
	<div class="row justify-content-md-center">
		<div class="col-md-3">
			<%= link_to "早速立ち上げる", new_circle_path, class: "btn btn-primary btn-lg active" %>
		</div>
	</div>
	<h3>ジャンル一覧</h3>
	<div class="row">
		<% @genres.each_with_index do |genre, n| %>
			<%= link_to circles_genre_path(genre: genre) do %>
				<div class="genre-images">
					<%= image_tag "genres/image#{n+1}.jpg", class:"circle-img" %>
					<p><%= genre.name %></p>
				</div>
			<% end %>
		<% end %>
	</div>
</div>

app/views/circles/new.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Create Circle</h2>
      <h5>サークルを立ち上げる</h5>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: @circle, local: true do |f| %>
        <%= render "/shared/error_message", model: f.object %>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :description %>
          </div>
          <div class='field-input'>
            <%= f.text_area :description, class:"form-control" %>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :genre_id %>
          </div>
          <div class='field-input'>
            <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"form-control"}) %>
          </div>
					<div class='field-label'>
            <%= f.label :activity_id %>
          </div>
          <div class='field-input'>
            <%= f.collection_select(:activity_id, Activity.all, :id, :name, {}, {class:"form-control"}) %>
          </div>
					<div class='field-label'>
            <%= f.label :age_range_id %>
          </div>
          <div class='field-input'>
            <%= f.collection_select(:age_range_id, AgeRange.all, :id, :name, {}, {class:"form-control"}) %>
          </div>
					<div class='field-label'>
            <%= f.label :prefecture_id %>
          </div>
          <div class='field-input'>
            <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"form-control"}) %>
          </div>
          <%= f.hidden_field :leader, :value => current_user.id %>
          <%= f.hidden_field :user_ids, :value => current_user.id %>
        </div>
        <div class='actions'>
          <%= f.submit "Create Account", class: 'btn'%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/circles/search.html.erb
<div class="container">
	<h3>検索</h3>
	<%= render "search_form", search: @p %>
	<h3>検索結果</h3>
	<br>
	<% if @results.length !=0 %>
		<% @results.each do |result| %>
			<div class="p-2 bd-highlight circle-list">
				<%= link_to result.name, circle_path(result) %>
				<br>
				<%= image_tag result.image, class: "circle-img" if result.image.attached?%>
				<%= result.phrase %>
			</div>
			<br>
		<% end %>
	<% end %>
</div>

app/views/circles/show.html.erb
<div class="container">
	<%= render "circle_head", circle: @circle %>
	<div class="link-field">
		<% if signed_in? && @circle.leader_user == current_user %>
			<%= link_to "編集", edit_circle_path(@circle), class: "btn btn-primary btn-lg" %>
			<%= link_to "削除", circle_path, method: :delete, data: {confirm: "本当に削除しますか？"} ,class: "btn btn-secondary btn-lg" %>
		<% end %>
		<% if @users.include?(current_user) %>
			<%= link_to "退会", circle_withdrawal_path(@circle), class: "btn btn-primary btn-lg" %>
		<% else %>
			<%= link_to "加入", circle_joing_path(@circle), class: "btn btn-primary btn-lg" %>
		<% end %>
	</div>
	<h2>サークル情報</h2>
	<ul class="list-group">
		<li class="list-group-item">サークル詳細説明：<br>
			<%= safe_join(@circle.description.split("\n"), tag(:br)) %></li>
		<li class="list-group-item">ジャンル：<%= @circle.genre.name %></li>
		<li class="list-group-item">活動日：<%= @circle.activity %></li>
		<li class="list-group-item">年齢層：<%= @circle.age_range %></li>
		<li class="list-group-item">活動場所：<%= @circle.prefecture.name %><%= @circle.city %></li>
	</ul>
	<h2>所属しているユーザー</h2>
	<ul class="list-group list-group-flush">
		<% @users.each do |user| %>
			<li class="list-group-item"><%= image_tag user.avatar, class: "user-avatar" if user.avatar.attached?%><%= user.nickname %></li>
		<% end %>
	</ul>
	<h2>活動日誌</h2>
	<%= link_to "新規作成", new_circle_article_path(@circle), class:"btn btn-primary" %>
	<ul class="list-group">
  	<% @articles.each do |article| %>
			<li class="list-group-item"><%= link_to article.title, circle_article_path(@circle, article) %></li>
		<% end %>
	</ul>
	<br>
	<% if @circle.users.include?(current_user) %>
		<h2>イベントスケジュール</h2>
		<%= link_to "新規イベント作成", new_circle_event_path(@circle), class: "btn btn-primary btn-lg" %>
		<%= month_calendar events: @events do |date, events| %>
			<%= date %>
			<% events.each do |event| %>
				<div>
					<%= link_to event.title, circle_event_path(@circle,event) %>
				</div>
			<% end %>
		<% end %>
	<% end %>
</div>